version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: borme_postgres
    environment:
      POSTGRES_DB: borme_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: