-- V2__Refactor_BormeFile_And_Create_Companies.sql

-- === FASE 1: REFACTORIZACIÓN DE LA TABLA EXISTENTE ===

-- Renombrar la tabla a borme_publications
ALTER TABLE borme_file RENAME TO borme_publications;

-- Añade columna para fecha de publicación
ALTER TABLE borme_publications ADD COLUMN publication_date DATE;

-- Renombrar columnas para adoptar snake_case
ALTER TABLE borme_publications RENAME COLUMN filename TO file_name;
ALTER TABLE borme_publications RENAME COLUMN path TO file_url;

-- Añade columna processed_at para consistencia con la entidad
ALTER TABLE borme_publications ADD COLUMN processed_at TIMESTAMP WITH TIME ZONE;


-- === FASE 2: CREACIÓN DE LA NUEVA TABLA DE COMPAÑÍAS ===

CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borme_id VARCHAR(255),
    name VARCHAR(255),
    act_type VARCHAR(255),
    object TEXT,
    address TEXT,
    capital VARCHAR(255),
    sole_partner VARCHAR(255),
    admin TEXT,
    registry_data TEXT,
    pdf_path VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE,

    -- La clave foránea que establece la relación maestra-detalle
    publication_id BIGINT NOT NULL,

    CONSTRAINT fk_company_to_publication
        FOREIGN KEY (publication_id)
        REFERENCES borme_publications(id)
);